apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: transmission-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        ports:
        - containerPort: 4180
          protocol: TCP
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: OAUTH2_PROXY_COOKIE_SECRET
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: OAUTH2_PROXY_CLIENT_SECRET
        args:
        - --provider=github
        - --email-domain=*
        - --upstream=static://200
        - --http-address=0.0.0.0:4180
        - --proxy-prefix=/oauth2        # Tells the proxy its base path
        - --cookie-secure=true
        - --cookie-httponly=true
        - --cookie-refresh=1h
        - --github-user=muchasxmaracas
        - --scope=user:email read:user
        - --set-xauthrequest=true
        - --reverse-proxy=true
        - --cookie-samesite=lax
        - --skip-provider-button=true        # <--- This kills the "Found" white page
        - --skip-auth-preflight=true         # <--- Helps with browser asset requests
        - --skip-auth-regex=^\/oauth2\/.*
        - --skip-auth-regex=^\/favicon\.ico$
        - --request-logging=true
        - --verbose=true
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: transmission-openvpn
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
---
# AUTH Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: transmission-auth
  namespace: transmission-openvpn
spec:
  forwardAuth:
    address: http://oauth2-proxy.transmission-openvpn.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Set-Cookie
    authRequestHeaders:
      - Cookie
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Forwarded-Method
      - Host
---
# REDIRECT Root Path Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: transmission-redirect
  namespace: transmission-openvpn
spec:
  redirectRegex:
    regex: "^https://transmission.baphomet.cloud/$"
    replacement: "https://transmission.baphomet.cloud/transmission/web/"
    permanent: true
---
# REDIRECT Signin Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-signin-redirect
  namespace: transmission-openvpn
spec:
  errors:
      status:
        - "401-403"
      service:
        name: oauth2-proxy
        port: 4180
      query: "/oauth2/start?rd={url}"
---
# Separate Ingress without middleware to prevent Traefik loops
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-public
  namespace: transmission-openvpn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - transmission.baphomet.cloud
    secretName: transmission-tls-secret
  rules:
  - host: transmission.baphomet.cloud # DOUBLE CHECK THE SPELLING
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180