apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pelican-db
spec:
  serviceName: pelican-db
  replicas: 1
  selector:
    matchLabels:
      app: pelican-db
  template:
    metadata:
      labels:
        app: pelican-db
    spec:
      containers:
      - name: pelican-db
        image: mariadb:11.4
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-config
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ {{ .Values.persistence.database.accessMode | quote }} ]
      resources:
        requests:
          storage: {{ .Values.persistence.database.size | quote }}