apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pelican-https-headers
  namespace: pelican
spec:
  headers:
    # Explicitly tell the backend the protocol is HTTPS
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
    # This prevents the "Infinite Loop" caused by Traefik trying to 
    # redirect HTTP to HTTPS at the same time as Caddy.
    sslRedirect: false