apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pelican-https-headers
  namespace: pelican
spec:
  headers:
    # This forces the header to 'https' for the backend
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    # This tells Traefik to trust the incoming TLS
    sslProxyHeaders:
      X-Forwarded-Proto: "https"