apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pelican
  labels:
    {{- include "pelican.labels" . | nindent 4 }}
spec:
  serviceName: pelican
  replicas: 1
  selector:
    matchLabels:
      {{- include "pelican.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pelican.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: pelican
        image: ghcr.io/shiipou/pelican-k8s/panel
        volumeMounts:
        - name: panel-data
          subPath: var
          mountPath: /app/var
        - name: panel-data
          subPath: storage
          mountPath: /app/storage
  volumeClaimTemplates:
  - metadata:
      name: panel-data
    spec:
      accessModes: [ {{ .Values.persistence.panel.accessMode | default "ReadWriteOnce" | quote }} ]
      resources:
        requests:
          storage: {{ .Values.persistence.panel.size | default "2Gi" | quote }}