apiVersion: v1
kind: ConfigMap
metadata:
  name: pelican-caddyfile
  namespace: pelican  # adjust if needed
data:
  Caddyfile: |
    {
        # Global options: disable all automatic HTTPS nonsense
        auto_https off
        # No email = no ACME attempts at all
        # admin off  (already in your original)
        servers {
            trusted_proxies static private_ranges  # matches your env var
        }
    }

    :80 {  # Serve plain HTTP internally on :80 (Traefik proxies here)
        root * /var/www/html/public
        encode gzip
        file_server
        php_fastcgi 127.0.0.1:9000  # Your PHP-FPM upstream
    }