apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pelican.fullname" . }}-secret-mgr
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pelican.fullname" . }}-secret-mgr-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pelican.fullname" . }}-secret-mgr-binding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pelican.fullname" . }}-secret-mgr-role
subjects:
- kind: ServiceAccount
  name: {{ include "pelican.fullname" . }}-secret-mgr
  namespace: {{ .Release.Namespace }}