apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pelican.fullname" . }}-secret-gen
  labels:
    {{- include "pelican.labels" . | nindent 4 }}
  annotations:
    # This is the magic: it runs before the install and is deleted after success
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "pelican.fullname" . }}-secret-mgr
      containers:
      - name: generate
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          if kubectl get secret mysql-config -n {{ .Release.Namespace }}; then
            echo "Secret already exists. Skipping generation."
          else
            PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24)
            kubectl create secret generic mysql-config \
              --from-literal=MARIADB_PASSWORD=$PASSWORD \
              --from-literal=DB_PASSWORD=$PASSWORD \
              -n {{ .Release.Namespace }}
            echo "Secret generated successfully."
          fi
      restartPolicy: OnFailure