{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "mysql-config") -}}
{{- if not $existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $pass := .Values.database.config.password | default (randAlphaNum 24) }}
  MARIADB_PASSWORD: {{ $pass | b64enc | quote }}
  DB_PASSWORD: {{ $pass | b64enc | quote }}
  MARIADB_ROOT_PASSWORD: {{ $pass | b64enc | quote }}
{{- end }}