apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pelican.fullname" . }}-secret-gen
  labels:
    {{- include "pelican.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "pelican.fullname" . }}-secret-mgr
      containers:
      - name: generate
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Check if secret exists
          if kubectl get secret mysql-config -n {{ .Release.Namespace }} > /dev/null 2>&1; then
            echo "Secret mysql-config already exists. Skipping."
          else
            echo "Generating new secure passwords..."
            # Generate two distinct passwords for security
            USER_PASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24)
            ROOT_PASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24)
            
            kubectl create secret generic mysql-config \
              --from-literal=MARIADB_USER={{ .Values.database.config.user | default "pelican" }} \
              --from-literal=MARIADB_PASSWORD=$USER_PASS \
              --from-literal=DB_PASSWORD=$USER_PASS \
              --from-literal=MARIADB_ROOT_PASSWORD=$ROOT_PASS \
              --from-literal=MARIADB_DATABASE={{ .Values.database.config.database | default "pelican" }} \
              -n {{ .Release.Namespace }}
            
            echo "Secret created with root and user credentials."
          fi
      restartPolicy: OnFailure