apiVersion: v1
kind: Service
metadata:
  name: wings
  namespace: pelican
spec:
  type: ClusterIP
  clusterIP: 10.43.200.200 # Locked forever
  selector:
    app: wings
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: sftp
      protocol: TCP
      port: 2022
      targetPort: 2022